Taks JDP200302-14 - encja carts
pplutap/JDP-2003-02 pull request #10
Opened 2020-04-02 11:15 UTC by dawid-walter

2020-04-02 13:15 UTC, pplutap requested changes

2020-04-02 13:15 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @JoinColumn(name = "GROUP_ID")
Czy powiązanie do grup jest potrzebne?

2020-04-02 14:03 UTC, NaliKod reviewed
Dodałabym do zminnej Id  @NotNull i do @Column dodałabym unique=true.

2020-04-02 14:27 UTC, magalera approved these changes

2020-04-02 14:27 UTC, magalera commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +@Entity(name = "CARTS")
```suggestion
@Entity
@Table(name = "CARTS")
```

2020-04-02 14:28 UTC, magalera commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +@Entity(name = "CARTS")
nazwa tabeli powinna być przy adnotacji @Table, a @Entity nad nią

2020-04-02 14:49 UTC, magalera approved these changes

2020-04-02 14:49 UTC, magalera commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @JoinColumn(name = "GROUP_ID")
Moim zdaniem tutaj potrzebna jest relacja M:N (wiele do wielu), łącząca usera z produktami, które ma aktualnie w koszyku.

2020-04-03 15:49 UTC, SirVertar approved these changes

2020-04-03 15:49 UTC, SirVertar commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    @JoinColumn(name = "GROUP_ID")
Moim zdaniem Group jest tu zbędne, powinno być raczej powiązane relacją ManyToMany z Product. Czy źle myślę ? A dalej Encja Order powinna być powiązana relacja ManyToMany z Twoim koszyczkiem :D Ale zapewne źle myślę

2020-04-03 17:40 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private String name;
Co będzie oznaczać `name`? Brakuje "powiązania" z produktem/produktami. Nie mam na myśli bezpośredniej relacji. Może `name` to `name` produktu?

2020-04-03 17:45 UTC, pplutap approved these changes

2020-04-03 17:45 UTC, merged