Zmiany kosmetyczne dla kontrolerow v1
pplutap/JDP-2003-02 pull request #15
Opened 2020-04-04 09:35 UTC by dawid-walter

Poprzedni branch z kontrolerami rozrosl sie na tyle, ze zaczal powodowac rozne problemy. Tak wiec ten jest zrobiony na swiezo i wyglada na to, ze jest w miare w porzadku

2020-04-04 15:17 UTC, SirVertar approved these changes

2020-04-04 19:33 UTC, pplutap approved these changes

2020-04-04 19:38 UTC, magalera requested changes

2020-04-04 19:38 UTC, magalera commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +@RequestMapping("/v1/groups")
```suggestion
@RequestMapping("/v1/group")
```

2020-04-04 19:38 UTC, magalera commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +@RequestMapping("/v1/products")
```suggestion
@RequestMapping("/v1/product")
```

2020-04-04 19:38 UTC, magalera commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public UserDto createUser(@RequestBody UserDto userDto) {
```suggestion
    public UserDto create(@RequestBody UserDto userDto) {
```

2020-04-04 19:38 UTC, magalera commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +@RequestMapping("/v1/users")
```suggestion
@RequestMapping("/v1/user")
```

2020-04-04 19:38 UTC, magalera commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public UserDto blockUser(@PathVariable() Long id) {
```suggestion
    public UserDto block(@PathVariable Long id) {
```

2020-04-04 19:38 UTC, magalera commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +    public Long generateKey(@PathVariable() Long id) {
```suggestion
    public Long generateKey(@PathVariable Long id) {
```

2020-04-05 06:46 UTC, dawid-walter commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +@RequestMapping("/v1/groups")
![image](https://user-images.githubusercontent.com/57115401/78468554-f9a8e900-7710-11ea-9d27-3748980484e3.png)
w API trello jest liczba mnoga, tu tez bym tak zostawil, w zasadzie bedziemy mieli w bazie dancyh wiele obiektow a nie tylko jeden.

2020-04-05 06:47 UTC, dawid-walter commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +@RequestMapping("/v1/products")
![image](https://user-images.githubusercontent.com/57115401/78468637-b00cce00-7711-11ea-9c2f-c2a8dacf0a12.png)

2020-04-05 09:26 UTC, magalera approved these changes

2020-04-05 16:10 UTC, merged