New Pull Request bc of problem with resolving conflict with master
pplutap/JDP-2003-02 pull request #18
Opened 2020-04-05 18:02 UTC by SirVertar

2020-04-05 20:15 UTC, pplutap commented
Brak nr taska w tytule

2020-04-05 20:48 UTC, SirVertar commented
> Brak nr taska w tytule

Sorki.

2020-04-06 05:09 UTC, pplutap requested changes

2020-04-06 05:09 UTC, pplutap commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        assertEquals(newTrousersDescription, actualTrousers.get().getDescription());
Aby porównać wartości powinieneś ponownie pobrać obiekt z bazy. W chwili obecnej, aktualizujesz wartość zmiennej w `actualTrousers` i porównujesz z tym samym obiektem

2020-04-06 06:31 UTC, SirVertar commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        assertEquals(newTrousersDescription, actualTrousers.get().getDescription());
Dzięki! Poprawię jak tylko wrócę do domu.

2020-04-08 15:03 UTC, NaliKod approved these changes

2020-04-08 17:04 UTC, magalera requested changes

2020-04-08 17:04 UTC, magalera commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +    public void testGetProduct() {
```suggestion
    public void testSaveProduct() {
  ```
Testujesz zapisywanie produktów, nie pobieranie.

2020-04-08 17:04 UTC, magalera commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        assertTrue(actualShirt.isPresent());
Mógłbyś jeszcze sprawdzić, czy produkty zapisały się do odpowiedniej grupy ;)

2020-04-08 17:04 UTC, magalera commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +
można by jeszcze zmienić nazwę produktu i przetestować czy również w danej grupie będzie ona zaktualizowana -  a powinna, ponieważ mamy ustawioną kaskadowość CascadeType.MERGE :)

2020-04-08 17:04 UTC, magalera commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        actualShirt = productRepository.findById(shirtId);
```suggestion
        
```

2020-04-08 17:04 UTC, magalera commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        actualShirt = productRepository.findById(shirtId);
Te linijki są zbędne, ponieważ przypisałeś już wcześniej wartość do actualTrousers, actualBoots i actualShirt.

2020-04-08 17:04 UTC, magalera commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        Optional<Product> actualShirt = productRepository.findById(shirtId);
```suggestion
      
```

2020-04-08 17:04 UTC, magalera commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        Optional<Product> actualShirt = productRepository.findById(shirtId);
Nie musimy pobierać tych produktów i zapisywać do zmiennych, ponieważ te zmienne nie są nam w tym teście potrzebne. Chcemy usunąć tylko trousers.

2020-04-08 17:04 UTC, magalera commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        assertTrue(actualShirt.isPresent());
```suggestion
        
```
Nie musisz sprawdzać czy te produkty istnieją, ponieważ sprawdzasz to już w pierwszym teście :)

2020-04-08 17:50 UTC, SirVertar commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        actualShirt = productRepository.findById(shirtId);
Jesteś pewna Małgosia? Nie muszę pobrać jeszcze raz obiektu z bazy danych po jego zapisaniu, tak aby pola były atkualne ?

2020-04-08 17:50 UTC, SirVertar commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        assertTrue(actualShirt.isPresent());
Jesteś pewna, że każdy test nie powinien stanowić tj odrębnej całości ?

2020-04-08 17:50 UTC, SirVertar commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        assertTrue(actualShirt.isPresent());
Coś wymyślę :)

2020-04-08 21:18 UTC, pplutap approved these changes

2020-04-08 23:04 UTC, magalera approved these changes

2020-04-08 23:04 UTC, magalera commented on src/test/java/com/kodilla/ecommercee/repository/ProductRepositoryTestSuite.java
> +        assertTrue(actualShirt.isPresent());
No tak, ale powyższych dwóch produktów w żaden sposób nie zmieniasz i nie usuwasz, tylko dodajesz na początku testu tak jak w poprzednim teście, więc uważam, że nie ma sensu weryfikować ich obecności ;)

2020-04-09 06:12 UTC, merged