First commit, task JDP200302-1, ProductController pre-implementation
pplutap/JDP-2003-02 pull request #2
Opened 2020-03-28 20:51 UTC by dawid-walter

2020-03-29 11:48 UTC, pplutap requested changes

2020-03-29 11:48 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +       return null;
Powinna być zwracana lista ze zmokowanymi danymi

2020-03-29 11:48 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +        return new ProductDto();
Warto przekazać "sztuczne" dane

2020-03-29 17:40 UTC, dawid-walter commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +        return new ProductDto();
Poprawione w najnowszym commicie

2020-03-29 17:40 UTC, dawid-walter commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +       return null;
poprawione wnajnowszym commicie

2020-03-30 11:45 UTC, dawid-walter reviewed
poprawki

2020-03-30 11:49 UTC, dawid-walter reviewed
poprawki

2020-03-30 12:18 UTC, dawid-walter commented on src/main/java/com/kodilla/ecommercee/ProductController.java
>      @GetMapping(value = "getProductById")
dodane zmiany zeby metoda zwracala zmokowane dane

2020-03-30 19:22 UTC, pplutap approved these changes

2020-03-30 19:34 UTC, merged