OrderController, method GET,PUT,POST,DEL
pplutap/JDP-2003-02 pull request #3
Opened 2020-03-29 12:39 UTC by NaliKod

Cześć Paweł,

Przesyłam OrderController do sprawdzenia.

Z góry dziękuję
Pozdrawiam
Karolina

2020-03-29 12:56 UTC, pplutap commented
Projek się nie buduje:
https://circleci.com/gh/pplutap/JDP-2003-02/12?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

2020-03-29 13:08 UTC, dawid-walter commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    private OrderMapper orderMapper;
Widze, ze "aplikacja" sie nie zbudowala, podejrzewam ze to przez probe wstrzykniecia OrderMapper (klasa nie istnieje u Ciebie w projekcie), wydaje mi sie ze narazie powinnismy zrobic "szkielet" metod najpierw a mappery bedziemy dodawac pozniej. Z mojej strony dodam, ze wstrzykiwanie zaleznosci poprzez pole jest nie wskazane, nawet intellij to podkresla.

2020-03-29 22:07 UTC, NaliKod commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    private OrderMapper orderMapper;
Przesyłam tym razem z klasami Order, OrderDto,OrderMapper

2020-03-30 07:19 UTC, pplutap commented
Branch zawiera konflikty z masterem - rozwiąż je proszę

2020-03-30 08:49 UTC, NaliKod commented
Cześć Paweł,

Poprawiłam build.gradle file. Mam nadzieje, że tym razem będzie lepiej.

2020-03-30 10:37 UTC, NaliKod commented
Po poprawie gralde.build

2020-03-30 19:29 UTC, pplutap requested changes

2020-03-30 19:29 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +        return orderMapper.mapToOrderDtoList(new ArrayList<>());
Powinny być zwracane "sztuczne" dane

2020-03-30 19:29 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    //private boolean isVerified;
Usuń proszę komentarze

2020-03-30 19:29 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +public class Order {
Na razie nie tworzymy encji

2020-03-30 19:29 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +   // private boolean isVerified;
Usuń proszę komentarze

2020-03-30 20:15 UTC, pplutap requested changes

2020-03-30 20:15 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +public class Order {
Na razie nie tworzymy encji, klasa nie jest potrzebna

2020-03-30 20:15 UTC, pplutap commented on src/main/java/com/kodilla/ecommercee/mapper/OrderMapper.java
> +        return new Order(
Takie mapowanie nie jest potrzebne jeśli nie mamy encji

2020-03-30 20:23 UTC, pplutap approved these changes

2020-03-30 20:44 UTC, merged